#! /usr/bin/env bash
set -euo pipefail

VERSION_JUST_CREATED="$1"
echo "Status pre changes"
git status

if [[ -f "./Cargo.toml" ]]; then
  cat Cargo.toml | toml-to-json | jq --arg newver "$VERSION_JUST_CREATED" '.package.version = $newver' | json-to-toml | sponge Cargo.toml
fi

if [[ -f "./info.rkt" ]]; then
  cat info.rkt | sed -e 's|(define version.*|(define version "'"$VERSION_JUST_CREATED"'")|' | sponge info.rkt
  raco exe --cs main.rkt
  raco distribute $RACO_PKG_NAME main
  tar czf $RACO_PKG_NAME.tar.gz $RACO_PKG_NAME
fi

if [[ -z ${SEMANTIC_RELEASE__NO_COMMIT_DURING_PREPARE:-""} ]]; then
  git add .
  git commit --allow-empty -m 'chore: semantic release auto'
fi
