#! /usr/bin/env bash
set -euo pipefail

VERSION_JUST_CREATED="$1"
echo "Status pre changes"
git status

if [[ -f "./Cargo.toml" ]]; then
  cat Cargo.toml | toml-to-json | jq --arg newver "$VERSION_JUST_CREATED" '.package.version = $newver' | json-to-toml | sponge Cargo.toml
  git add Cargo.toml
  git commit -m "chore: auto update cargo.toml version"
fi

if [[ -f "./info.rkt" ]]; then
  VERSION_JUST_CREATED="v$VERSION_JUST_CREATED"
  cat info.rkt | sed -e 's|(define version.*|(define version "'"$VERSION_JUST_CREATED"'")|' | sponge info.rkt
  git add info.rkt
  git commit -m "chore: auto update racket info.rkt version"
fi

# https://gitlab.com/jackmac92/href-router-racket/-/jobs/2712456036
# disabling below because it commits in detached head state, hopefully semantic release picks this up and autocommits it?
# git commit --allow-empty -m 'chore: semantic release auto'
